package Fin;

import Nats.S;
import Nats.Z;
import static Fin.Fin.FZ.*;
import static Fin.Fin.FS.*;

public class Fins {
  public static Fin<S<Z>>                                     at0of1 = fz();
  public static Fin<S<S<Z>>>                                  at0of2 = fz();
  public static Fin<S<S<Z>>>                                  at1of2 = fs(fz());
  public static Fin<S<S<S<Z>>>>                               at0of3 = fz();
  public static Fin<S<S<S<Z>>>>                               at1of3 = fs(fz());
  public static Fin<S<S<S<Z>>>>                               at2of3 = fs(fs(fz()));
  public static Fin<S<S<S<S<Z>>>>>                            at0of4 = fz();
  public static Fin<S<S<S<S<Z>>>>>                            at1of4 = fs(fz());
  public static Fin<S<S<S<S<Z>>>>>                            at2of4 = fs(fs(fz()));
  public static Fin<S<S<S<S<Z>>>>>                            at3of4 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<Z>>>>>>                         at0of5 = fz();
  public static Fin<S<S<S<S<S<Z>>>>>>                         at1of5 = fs(fz());
  public static Fin<S<S<S<S<S<Z>>>>>>                         at2of5 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<Z>>>>>>                         at3of5 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<Z>>>>>>                         at4of5 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at0of6 = fz();
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at1of6 = fs(fz());
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at2of6 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at3of6 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at4of6 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<Z>>>>>>>                      at5of6 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at0of7 = fz();
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at1of7 = fs(fz());
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at2of7 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at3of7 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at4of7 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at5of7 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<Z>>>>>>>>                   at6of7 = fs(fs(fs(fs(fs(fs(fz()))))));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at0of8 = fz();
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at1of8 = fs(fz());
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at2of8 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at3of8 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at4of8 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at5of8 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at6of8 = fs(fs(fs(fs(fs(fs(fz()))))));
  public static Fin<S<S<S<S<S<S<S<S<Z>>>>>>>>>                at7of8 = fs(fs(fs(fs(fs(fs(fs(fz())))))));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at0of9 = fz();
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at1of9 = fs(fz());
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at2of9 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at3of9 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at4of9 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at5of9 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at6of9 = fs(fs(fs(fs(fs(fs(fz()))))));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at7of9 = fs(fs(fs(fs(fs(fs(fs(fz())))))));
  public static Fin<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>             at8of9 = fs(fs(fs(fs(fs(fs(fs(fs(fz()))))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at0of10 = fz();
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at1of10 = fs(fz());
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at2of10 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at3of10 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at4of10 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at5of10 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at6of10 = fs(fs(fs(fs(fs(fs(fz()))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at7of10 = fs(fs(fs(fs(fs(fs(fs(fz())))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at8of10 = fs(fs(fs(fs(fs(fs(fs(fs(fz()))))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>       at9of10 = fs(fs(fs(fs(fs(fs(fs(fs(fs(fz())))))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at0of11 = fz();
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at1of11 = fs(fz());
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at2of11 = fs(fs(fz()));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at3of11 = fs(fs(fs(fz())));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at4of11 = fs(fs(fs(fs(fz()))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at5of11 = fs(fs(fs(fs(fs(fz())))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at6of11 = fs(fs(fs(fs(fs(fs(fz()))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at7of11 = fs(fs(fs(fs(fs(fs(fs(fz())))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at8of11 = fs(fs(fs(fs(fs(fs(fs(fs(fz()))))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at9of11 = fs(fs(fs(fs(fs(fs(fs(fs(fs(fz())))))))));
  public static Fin<S<S<S<S<S<S<S<S<S<S<S<S<S<Z>>>>>>>>>>>>>> at10of11 = fs(fs(fs(fs(fs(fs(fs(fs(fs(fs(fz()))))))))));

}
